[project]
name = "ai-eng-week-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prashant Singh", email = "prasahntsingh4007@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "pydantic[email]>=2.13.5",
    "pydentic>=0.0.1.dev3",
]

[project.scripts]
ai-eng-week-1 = "ai_eng_week_1:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
